<a href="https://colab.research.google.com/github/Riaaggarwal06/Hackbattle-/blob/main/HackHers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import tensorflow as tf
from tensorflow import keras

In [41]:
!pip install -q streamlit

In [42]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [43]:
dataset = pd.read_csv('heart_disease.csv')

In [44]:
mapping = {'yes': 1, 'no': 0}
dataset['prevalentStroke'] = dataset['prevalentStroke'].map(mapping)
mapping = {'yes': 1, 'No': 0}
dataset['Heart_ stroke'] = dataset['Heart_ stroke'].map(mapping)
mapping = {'Male': 1, 'Female': 0}
dataset['Gender'] = dataset['Gender'].map(mapping)

In [45]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [46]:
print(X)

[[  1.    39.     0.   ...  26.97  80.    77.  ]
 [  0.    46.     0.   ...  28.73  95.    76.  ]
 [  1.    48.     1.   ...  25.34  75.    70.  ]
 ...
 [  0.    48.     1.   ...  22.    84.    86.  ]
 [  0.    44.     1.   ...  19.16  86.      nan]
 [  0.    52.     0.   ...  21.47  80.   107.  ]]


In [47]:
print(y)

[0 0 0 ... 0 0 0]


In [48]:
dataset.isnull().sum()

Gender               0
age                  0
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
Heart_ stroke        0
dtype: int64

In [49]:
dataset

Gender  age  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0          1   39              0         0.0     0.0                0   
1          0   46              0         0.0     0.0                0   
2          1   48              1        20.0     0.0                0   
3          0   61              1        30.0     0.0                0   
4          0   46              1        23.0     0.0                0   
...      ...  ...            ...         ...     ...              ...   
4233       1   50              1         1.0     0.0                0   
4234       1   51              1        43.0     0.0                0   
4235       0   48              1        20.0     NaN                0   
4236       0   44              1        15.0     0.0                0   
4237       0   52              0         0.0     0.0                0   

      prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  \
0                0         0    195.0  106.0   70.0  26.97       80.0   
1                0         0    250.0  121.0   81.0  28.73       95.0   
2                0         0    245.0  127.5   80.0  25.34       75.0   
3                1         0    225.0  150.0   95.0  28.58       65.0   
4                0         0    285.0  130.0   84.0  23.10       85.0   
...            ...       ...      ...    ...    ...    ...        ...   
4233             1         0    313.0  179.0   92.0  25.97       66.0   
4234             0         0    207.0  126.5   80.0  19.71       65.0   
4235             0         0    248.0  131.0   72.0  22.00       84.0   
4236             0         0    210.0  126.5   87.0  19.16       86.0   
4237             0         0    269.0  133.5   83.0  21.47       80.0   

      glucose  Heart_ stroke  
0        77.0              0  
1        76.0              0  
2        70.0              0  
3       103.0              1  
4        85.0              0  
...       ...            ...  
4233     86.0              1  
4234     68.0              0  
4235     86.0              0  
4236      NaN              0  
4237    107.0              0  

[4238 rows x 15 columns]

hello

In [50]:
dataset['prevalentStroke'].value_counts()

0    4213
1      25
Name: prevalentStroke, dtype: int64

In [51]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 3:15])
X[:, 3:15] = imputer.transform(X[:, 3:15])

In [52]:
print(X)

[[  1.          39.           0.         ...  26.97        80.
   77.        ]
 [  0.          46.           0.         ...  28.73        95.
   76.        ]
 [  1.          48.           1.         ...  25.34        75.
   70.        ]
 ...
 [  0.          48.           1.         ...  22.          84.
   86.        ]
 [  0.          44.           1.         ...  19.16        86.
   81.96675325]
 [  0.          52.           0.         ...  21.47        80.
  107.        ]]


In [53]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [54]:
print(X)

[[  1.           0.           1.         ...  26.97        80.
   77.        ]
 [  1.           0.           0.         ...  28.73        95.
   76.        ]
 [  0.           1.           1.         ...  25.34        75.
   70.        ]
 ...
 [  0.           1.           0.         ...  22.          84.
   86.        ]
 [  0.           1.           0.         ...  19.16        86.
   81.96675325]
 [  1.           0.           0.         ...  21.47        80.
  107.        ]]


In [55]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [56]:
print(y)

[0 0 0 ... 0 0 0]


In [57]:
print(X)

[[  1.           0.           1.         ...  26.97        80.
   77.        ]
 [  1.           0.           0.         ...  28.73        95.
   76.        ]
 [  0.           1.           1.         ...  25.34        75.
   70.        ]
 ...
 [  0.           1.           0.         ...  22.          84.
   86.        ]
 [  0.           1.           0.         ...  19.16        86.
   81.96675325]
 [  1.           0.           0.         ...  21.47        80.
  107.        ]]


In [58]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)


In [59]:
print(X_train)


[[ 1.    0.    0.   ... 19.91 66.   85.  ]
 [ 0.    1.    0.   ... 27.78 95.   74.  ]
 [ 0.    1.    1.   ... 22.7  75.   98.  ]
 ...
 [ 0.    1.    1.   ... 24.47 70.   81.  ]
 [ 1.    0.    0.   ... 24.27 75.   81.  ]
 [ 0.    1.    0.   ... 26.56 75.   73.  ]]


In [60]:
print(y_train)

[0 0 1 ... 0 0 0]


In [61]:
print(X_test)

[[ 1.          0.          0.         ... 27.64       75.
  62.        ]
 [ 1.          0.          0.         ... 23.36       60.
  73.        ]
 [ 0.          1.          0.         ... 38.46       57.
  78.        ]
 ...
 [ 1.          0.          0.         ... 26.22       62.
  75.        ]
 [ 1.          0.          1.         ... 28.7        72.
  81.96675325]
 [ 0.          1.          0.         ... 22.91       75.
  70.        ]]


In [62]:
print(y_test)

[0 0 0 ... 0 0 1]


In [63]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [64]:
print(X_train)

[[ 1.00694672 -1.00694672 -0.86936822 ... -1.44678609 -0.81568787
   0.12859984]
 [-0.9931012   0.9931012  -0.86936822 ...  0.48838803  1.59216957
  -0.35383715]
 [-0.9931012   0.9931012   1.15026059 ... -0.76074597 -0.06842177
   0.69875264]
 ...
 [-0.9931012   0.9931012   1.15026059 ... -0.32551621 -0.48356961
  -0.04683179]
 [ 1.00694672 -1.00694672 -0.86936822 ... -0.37469471 -0.06842177
  -0.04683179]
 [-0.9931012   0.9931012  -0.86936822 ...  0.18839915 -0.06842177
  -0.39769505]]


In [65]:
print(X_test)

[[ 1.00694672 -1.00694672 -0.86936822 ...  0.45396307 -0.06842177
  -0.88013204]
 [ 1.00694672 -1.00694672 -0.86936822 ... -0.5984569  -1.31386528
  -0.39769505]
 [-0.9931012   0.9931012  -0.86936822 ...  3.11452013 -1.56295398
  -0.17840552]
 ...
 [ 1.00694672 -1.00694672 -0.86936822 ...  0.1047957  -1.14780614
  -0.30997924]
 [ 1.00694672 -1.00694672  1.15026059 ...  0.71460914 -0.31751047
  -0.00443202]
 [-0.9931012   0.9931012  -0.86936822 ... -0.70910854 -0.06842177
  -0.52926878]]


In [66]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [67]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 1]]


In [68]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[884   6]
 [159  11]]


0.8443396226415094

In [69]:
import streamlit as st
import pandas as pd
import numpy as np
import pickle

st.write("""
Hello Users,
Welcome Heart Catalyst: It assist you with the risk prediction
This app predicts heart stroke.

""")

st.sidebar.header('User Input Features')

def user_input_features():
    age = st.sidebar.number_input("Age:")

    sex = st.sidebar.selectbox("Sex", ("Male", "Female"))
    sex = 0 if sex == "Female" else 1

    # education= st.sidebar.selectbox("Education:", ("PrimarySchool","Graduate","PostGraduate","Uneducated"))
    # education = 0
    # if education =="PrimarySchool":

    # elif "PrimarySchool","Graduate","PostGraduate","Uneducated"

    currsmoker = st.sidebar.selectbox('Current Smoker',(0,1))
    nocig = st.sidebar.number_input("Number of Ciggrates")
    bpmed = st.sidebar.selectbox('blood pressure meds',(0,1))

    prevstroke = st.sidebar.selectbox("Prevalent Stroke", ("Yes", "No"))
    prevstroke = 0 if prevstroke== "Yes" else 1

    prevhyp = st.sidebar.selectbox("Prevalent HYP", (0, 1))
    diabetes = st.sidebar.selectbox("diabetes", (0, 1))
    cholestrol = st.sidebar.number_input("cholestrol")

    data = {'age': age,
            'sex': sex,
            'currentSmoker' : currsmoker,
            'cigsPerDay' : nocig,
            'BPMeds' : bpmed,
            'prevalentStroke' : prevstroke,
            'prevalentHyp' : prevhyp,
            'diabetes' : diabetes,
            'totChol' : cholestrol,
            }

    features = pd.DataFrame(data, index=[0])
    return features
input_df = user_input_features()

heart_dataset = pd.read_csv('heart_disease.csv')
heart_dataset = heart_dataset.drop(columns=['target'])
df = pd.concat([input_df,heart_dataset],axis=0)

df = pd.get_dummies(df, columns = ['sex', 'education', 'currentSmoker', 'BPMeds', 'prevalentStroke', 'prevalentHyp', 'diabetes'])

df = df[:1]

st.write(input_df)
load_clf = pickle.load(open('Random_forest_model.pkl', 'rb'))

prediction = load_clf.predict(df)
prediction_proba = load_clf.predict_proba(df)

st.subheader('Prediction')
st.write(prediction)

st.subheader('Prediction Probability')
st.write(prediction_proba)

KeyError: ignored

In [ ]:
!npm install localtunnel

In [ ]:
!streamlit run /content/app.py &>/content/logs.txt &

In [ ]:
import urllib
print("Password/Enpoint IP for localtunnel is:",urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip("\n"))

In [ ]:
!npx localtunnel --port 8501

In [ ]:
!npm install localtunnel

In [ ]:
!streamlit run /content/app.py &>/content/logs.txt &

In [ ]:
import urllib
print("Password/Enpoint IP for localtunnel is:",urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip("\n"))

In [ ]:
!npx localtunnel --port 8501